import React from 'react';
import Head from 'next/head';
import Script from 'next/script';

const Login = () => {
    return (
        <>
            <Head>
                <title>Sign In</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="My pc, gaming pc, " />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="/check.css" />
                <link rel="icon" type="image/png" href="images/icons/favicon.ico" />

                <link rel="stylesheet" type="text/css" href="/login/vendor/bootstrap/css/bootstrap.min.css" />

                <link rel="stylesheet" type="text/css" href="/login/fonts/font-awesome-4.7.0/css/font-awesome.min.css" />

                <link rel="stylesheet" type="text/css" href="/login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css" />

                <link rel="stylesheet" type="text/css" href="/login/vendor/animate/animate.css" />

                <link rel="stylesheet" type="text/css" href="/login/vendor/css-hamburgers/hamburgers.min.css" />

                <link rel="stylesheet" type="text/css" href="/login/vendor/animsition/css/animsition.min.css" />

                <link rel="stylesheet" type="text/css" href="/login/vendor/select2/select2.min.css" />

                <link rel="stylesheet" type="text/css" href="/login/vendor/daterangepicker/daterangepicker.css" />

            </Head>
            <Script src='/login/vendor/jquery/jquery-3.2.1.min.js' />
            <Script src='/login/vendor/bootstrap/js/popper.js' />
            <Script src='/login/vendor/bootstrap/js/bootstrap.min.js' />
            {/* <Script src='/vendor/animsition/js/animsition.js' /> */}
            <Script src='/login/vendor/select2/select2.min.js' />
            <Script src='/login/vendor/daterangepicker/moment.min.js' />
            <Script src='/login/vendor/daterangepicker/daterangepicker.js' />
            <Script src='/login/vendor/countdowntime/countdowntime.js' />
            <Script src='/login/js/main.js' />
            <div className="limiter">
                <div className="container-login100">
                    <div className="wrap-login100">
                        <div className="login100-form-title" style={{
                            backgroundImage: 'url(/login/images/bg-01.jpg)'
                        }}>
                            <span className="login100-form-title-1">
                                Sign In
                            </span>
                        </div>

                        <form className="login100-form validate-form">
                            <div className="wrap-input100 validate-input m-b-26" data-validate="Username is required">
                                <span className="label-input100">Username</span>
                                <input className="input100" type="text" name="username" placeholder="Enter username" />
                                <span className="focus-input100"></span>
                            </div>

                            <div className="wrap-input100 validate-input m-b-18" data-validate="Password is required">
                                <span className="label-input100 ">Password</span>
                                <input className="input100" type="password" name="pass" placeholder="Enter password" />
                                <span className="focus-input100"></span>
                            </div>

                            <div className="flex-sb-m w-full p-b-30">
                                <div className="contact100-form-checkbox">
                                    <input className="input-checkbox100" id="ckb1" type="checkbox" name="remember-me" />
                                    <label className="label-checkbox100" htmlFor="ckb1">
                                        Remember me
                                    </label>
                                </div>

                                <div>
                                    <a href="#" className="txt1">
                                        Forgot Password?
                                    </a>
                                </div>
                            </div>

                            <div className="container-login100-form-btn">
                                <button className="login100-form-btn">
                                    Login
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </>
    )
}

export default Login
