import React, { useState } from 'react'
import Head from 'next/head';
const Header = () => {
    const [title, setTitle] = useState("Chat GPT");
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="My pc, gaming pc, " />
                {/* <link rel="icon" href="/favicon.ico" /> */}
                <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
                <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet" />
                <link href="/main/assets/css/bootstrap.min.css" rel="stylesheet" />
                <link href="/main/assets/css/paper-dashboard.css?v=2.0.1" rel="stylesheet" />
                <link href="/main/assets/demo/demo.css" rel="stylesheet" />
            </Head>
        </>
    )
}

export default Header
